/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ItServicesRouteImport } from './routes/it-services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItServicesIndexRouteImport } from './routes/it-services.index'
import { Route as ItServicesCategoryRouteImport } from './routes/it-services.$category'

const ItServicesRoute = ItServicesRouteImport.update({
  id: '/it-services',
  path: '/it-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItServicesIndexRoute = ItServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ItServicesRoute,
} as any)
const ItServicesCategoryRoute = ItServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ItServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/it-services': typeof ItServicesRouteWithChildren
  '/it-services/$category': typeof ItServicesCategoryRoute
  '/it-services/': typeof ItServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/it-services/$category': typeof ItServicesCategoryRoute
  '/it-services': typeof ItServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/it-services': typeof ItServicesRouteWithChildren
  '/it-services/$category': typeof ItServicesCategoryRoute
  '/it-services/': typeof ItServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/it-services'
    | '/it-services/$category'
    | '/it-services/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/it-services/$category' | '/it-services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/it-services'
    | '/it-services/$category'
    | '/it-services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ItServicesRoute: typeof ItServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/it-services': {
      id: '/it-services'
      path: '/it-services'
      fullPath: '/it-services'
      preLoaderRoute: typeof ItServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-services/': {
      id: '/it-services/'
      path: '/'
      fullPath: '/it-services/'
      preLoaderRoute: typeof ItServicesIndexRouteImport
      parentRoute: typeof ItServicesRoute
    }
    '/it-services/$category': {
      id: '/it-services/$category'
      path: '/$category'
      fullPath: '/it-services/$category'
      preLoaderRoute: typeof ItServicesCategoryRouteImport
      parentRoute: typeof ItServicesRoute
    }
  }
}

interface ItServicesRouteChildren {
  ItServicesCategoryRoute: typeof ItServicesCategoryRoute
  ItServicesIndexRoute: typeof ItServicesIndexRoute
}

const ItServicesRouteChildren: ItServicesRouteChildren = {
  ItServicesCategoryRoute: ItServicesCategoryRoute,
  ItServicesIndexRoute: ItServicesIndexRoute,
}

const ItServicesRouteWithChildren = ItServicesRoute._addFileChildren(
  ItServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ItServicesRoute: ItServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
